# Generated by Django 4.2.1 on 2023-05-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_like_date_alter_post_date_alter_post_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='athor',
            new_name='author',
        ),
    ]
