# Generated by Django 4.2.1 on 2023-05-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_athor_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='athor',
            new_name='author',
        ),
    ]
