# Generated by Django 4.2.1 on 2023-05-23 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_subscription_subscribed_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscribed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
