# Generated by Django 4.2.1 on 2023-05-24 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_subscription_subscribed_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscribed_user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='subscription',
            name='follower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscribers',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
